package com.example.proyectoversion1.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF675973)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFF5E4FF)
val onPrimaryContainerLight = Color(0xFF544760)
val secondaryLight = Color(0xFF8035C7)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFBF80FF)
val onSecondaryContainerLight = Color(0xFF1B0035)
val tertiaryLight = Color(0xFF3753C8)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF8096FF)
val onTertiaryContainerLight = Color(0xFF000938)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFEF8FA)
val onBackgroundLight = Color(0xFF1D1B1D)
val surfaceLight = Color(0xFFFEF8FA)
val onSurfaceLight = Color(0xFF1D1B1D)
val surfaceVariantLight = Color(0xFFE8E0E8)
val onSurfaceVariantLight = Color(0xFF4A454C)
val outlineLight = Color(0xFF7B757D)
val outlineVariantLight = Color(0xFFCCC4CC)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF323032)
val inverseOnSurfaceLight = Color(0xFFF5EFF2)
val inversePrimaryLight = Color(0xFFD2C0DE)
val surfaceDimLight = Color(0xFFDED9DB)
val surfaceBrightLight = Color(0xFFFEF8FA)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8F2F4)
val surfaceContainerLight = Color(0xFFF2ECEF)
val surfaceContainerHighLight = Color(0xFFECE7E9)
val surfaceContainerHighestLight = Color(0xFFE6E1E3)

val primaryLightMediumContrast = Color(0xFF4B3E56)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF7E6F8A)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF6204A9)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF974FDF)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF1034AC)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF506BE0)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFEF8FA)
val onBackgroundLightMediumContrast = Color(0xFF1D1B1D)
val surfaceLightMediumContrast = Color(0xFFFEF8FA)
val onSurfaceLightMediumContrast = Color(0xFF1D1B1D)
val surfaceVariantLightMediumContrast = Color(0xFFE8E0E8)
val onSurfaceVariantLightMediumContrast = Color(0xFF464148)
val outlineLightMediumContrast = Color(0xFF635D64)
val outlineVariantLightMediumContrast = Color(0xFF7F7980)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF323032)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF5EFF2)
val inversePrimaryLightMediumContrast = Color(0xFFD2C0DE)
val surfaceDimLightMediumContrast = Color(0xFFDED9DB)
val surfaceBrightLightMediumContrast = Color(0xFFFEF8FA)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF8F2F4)
val surfaceContainerLightMediumContrast = Color(0xFFF2ECEF)
val surfaceContainerHighLightMediumContrast = Color(0xFFECE7E9)
val surfaceContainerHighestLightMediumContrast = Color(0xFFE6E1E3)

val primaryLightHighContrast = Color(0xFF291D34)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF4B3E56)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF350060)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF6204A9)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF001866)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF1034AC)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFEF8FA)
val onBackgroundLightHighContrast = Color(0xFF1D1B1D)
val surfaceLightHighContrast = Color(0xFFFEF8FA)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE8E0E8)
val onSurfaceVariantLightHighContrast = Color(0xFF262329)
val outlineLightHighContrast = Color(0xFF464148)
val outlineVariantLightHighContrast = Color(0xFF464148)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF323032)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFF7E7FF)
val surfaceDimLightHighContrast = Color(0xFFDED9DB)
val surfaceBrightLightHighContrast = Color(0xFFFEF8FA)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF8F2F4)
val surfaceContainerLightHighContrast = Color(0xFFF2ECEF)
val surfaceContainerHighLightHighContrast = Color(0xFFECE7E9)
val surfaceContainerHighestLightHighContrast = Color(0xFFE6E1E3)

val primaryDark = Color(0xFFFFFFFF)
val onPrimaryDark = Color(0xFF382B43)
val primaryContainerDark = Color(0xFFE0CEEC)
val onPrimaryContainerDark = Color(0xFF473A52)
val secondaryDark = Color(0xFFDCB8FF)
val onSecondaryDark = Color(0xFF490081)
val secondaryContainerDark = Color(0xFF974FDF)
val onSecondaryContainerDark = Color(0xFFFFFFFF)
val tertiaryDark = Color(0xFFB9C3FF)
val onTertiaryDark = Color(0xFF002389)
val tertiaryContainerDark = Color(0xFF506BE0)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF141315)
val onBackgroundDark = Color(0xFFE6E1E3)
val surfaceDark = Color(0xFF141315)
val onSurfaceDark = Color(0xFFE6E1E3)
val surfaceVariantDark = Color(0xFF4A454C)
val onSurfaceVariantDark = Color(0xFFCCC4CC)
val outlineDark = Color(0xFF958F96)
val outlineVariantDark = Color(0xFF4A454C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE6E1E3)
val inverseOnSurfaceDark = Color(0xFF323032)
val inversePrimaryDark = Color(0xFF675973)
val surfaceDimDark = Color(0xFF141315)
val surfaceBrightDark = Color(0xFF3B383A)
val surfaceContainerLowestDark = Color(0xFF0F0E0F)
val surfaceContainerLowDark = Color(0xFF1D1B1D)
val surfaceContainerDark = Color(0xFF211F21)
val surfaceContainerHighDark = Color(0xFF2B292B)
val surfaceContainerHighestDark = Color(0xFF363436)

val primaryDarkMediumContrast = Color(0xFFFFFFFF)
val onPrimaryDarkMediumContrast = Color(0xFF382B43)
val primaryContainerDarkMediumContrast = Color(0xFFE0CEEC)
val onPrimaryContainerDarkMediumContrast = Color(0xFF261B31)
val secondaryDarkMediumContrast = Color(0xFFDFBDFF)
val onSecondaryDarkMediumContrast = Color(0xFF240045)
val secondaryContainerDarkMediumContrast = Color(0xFFB66EFF)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFBEC8FF)
val onTertiaryDarkMediumContrast = Color(0xFF000E4A)
val tertiaryContainerDarkMediumContrast = Color(0xFF6E88FF)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF141315)
val onBackgroundDarkMediumContrast = Color(0xFFE6E1E3)
val surfaceDarkMediumContrast = Color(0xFF141315)
val onSurfaceDarkMediumContrast = Color(0xFFFFF9FC)
val surfaceVariantDarkMediumContrast = Color(0xFF4A454C)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD0C8D1)
val outlineDarkMediumContrast = Color(0xFFA7A1A9)
val outlineVariantDarkMediumContrast = Color(0xFF878189)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE6E1E3)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2B292B)
val inversePrimaryDarkMediumContrast = Color(0xFF50435B)
val surfaceDimDarkMediumContrast = Color(0xFF141315)
val surfaceBrightDarkMediumContrast = Color(0xFF3B383A)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0F0E0F)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1D1B1D)
val surfaceContainerDarkMediumContrast = Color(0xFF211F21)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2B292B)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF363436)

val primaryDarkHighContrast = Color(0xFFFFFFFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFE0CEEC)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFFF9FC)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFDFBDFF)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFCFAFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFBEC8FF)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF141315)
val onBackgroundDarkHighContrast = Color(0xFFE6E1E3)
val surfaceDarkHighContrast = Color(0xFF141315)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF4A454C)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFF9FC)
val outlineDarkHighContrast = Color(0xFFD0C8D1)
val outlineVariantDarkHighContrast = Color(0xFFD0C8D1)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE6E1E3)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF31253C)
val surfaceDimDarkHighContrast = Color(0xFF141315)
val surfaceBrightDarkHighContrast = Color(0xFF3B383A)
val surfaceContainerLowestDarkHighContrast = Color(0xFF0F0E0F)
val surfaceContainerLowDarkHighContrast = Color(0xFF1D1B1D)
val surfaceContainerDarkHighContrast = Color(0xFF211F21)
val surfaceContainerHighDarkHighContrast = Color(0xFF2B292B)
val surfaceContainerHighestDarkHighContrast = Color(0xFF363436)














